-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["manux_Tiles_Devices_01_0"] = {{ name = "other", chance = 1, usage = "", tiles = {"manux_Tiles_Devices_01_3", "manux_Tiles_Devices_01_4"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
