-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["manux_Tiles_Devices_01_0"] = {{ name = "other", tiles = {"manux_Tiles_Devices_01_1", "manux_Tiles_Devices_01_2"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
